#!/bin/bash

#SBATCH --gres=gpu:1
#SBATCH --job-name=TestTraining
#SBATCH --ntasks=1
#SBATCH --partition=gpu_titanrtx_shared_course
#SBATCH --cpus-per-task=3
#SBATCH --time=00:10:00
#SBATCH --mem=32000M
#SBATCH --output=job_logs/test-training-models_%A.out

module purge
module load 2021
module load Anaconda3/2021.05

cd $HOME/DL2-2023-group-15/code/Asyrp_official
source activate asyrp

srun bash script_train.sh