#!/bin/bash

#SBATCH --gres=gpu:1
#SBATCH --job-name=AsyrpTest
#SBATCH --ntasks=1
#SBATCH --partition=gpu_titanrtx_shared_course
#SBATCH --cpus-per-task=3
#SBATCH --time=01:00:00
#SBATCH --mem=32000M
#SBATCH --output=src/jobs/job_logs/test_%A.out

module purge
module load 2021
module load Anaconda3/2021.05

cd $HOME/DL2-2023-group-15/src/lib/asyrp
source activate asyrp

bash scripts/script_inference_neanderthal.sh
bash scripts/script_inference_frida.sh