#!/bin/bash

#SBATCH --gres=gpu:1
#SBATCH --job-name=TransfAsyrpH1
#SBATCH --ntasks=1
#SBATCH --partition=gpu_titanrtx_shared_course
#SBATCH --cpus-per-task=3
#SBATCH --time=05:00:00
#SBATCH --mem=32000M
#SBATCH --output=src/jobs/job_logs/train_h1_modigliani_%A.out

module purge
module load 2021
module load Anaconda3/2021.05

cd $HOME/DL2-2023-group-15/src/lib/asyrp
source activate asyrp

# train modigliani h1 without transfer
bash scripts/ablations/simple_transformer/transfer_learning/train_transformer_modigliani_cp_h1.sh