#!/bin/bash

#SBATCH --gres=gpu:1
#SBATCH --job-name=FIDTable
#SBATCH --ntasks=1
#SBATCH --partition=gpu_titanrtx_shared_course
#SBATCH --cpus-per-task=3
#SBATCH --time=08:00:00
#SBATCH --mem=32000M
#SBATCH --output=src/jobs/job_logs/fid_table_neanderthal_nheads_8_%A.out

module purge
module load 2021
module load Anaconda3/2021.05

cd $HOME/DL2-2023-group-15/src/lib/asyrp
source activate asyrp

bash scripts/ablations/simple_transformer/fid_table/script_train_tranformer_neanderthal_pc_h8.sh